import { Category, Product, Coupon, Review } from '@/types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Home Décor',
    slug: 'home-decor',
    description: 'Artisan handcrafted accents to infuse serenity and warmth into every corner of your living spaces.',
    imageUrl: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=1000&auto=format&fit=crop',
    displayOrder: 1,
    status: 'Active',
  },
  {
    id: 'cat-2',
    name: 'Resin Crafts',
    slug: 'resin-crafts',
    description: 'Crystalline botanical preservation, gilded ocean waves, and luminous epoxy art pieces.',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1000&auto=format&fit=crop',
    displayOrder: 2,
    status: 'Active',
  },
  {
    id: 'cat-3',
    name: 'Personalized Gifts',
    slug: 'personalized-gifts',
    description: 'Custom inscribed keepsakes, bespoke name plaques, and engraved artisanal treasures.',
    imageUrl: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?q=80&w=1000&auto=format&fit=crop',
    displayOrder: 3,
    status: 'Active',
  },
  {
    id: 'cat-4',
    name: 'Wall Art',
    slug: 'wall-art',
    description: 'Textured canvas strokes, botanical macramé tapestries, and hand-painted wall statements.',
    imageUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=1000&auto=format&fit=crop',
    displayOrder: 4,
    status: 'Active',
  },
  {
    id: 'cat-5',
    name: 'Handmade Jewellery',
    slug: 'handmade-jewellery',
    description: 'Wearable art, polymer clay earrings, and delicate natural gemstone adornments.',
    imageUrl: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1000&auto=format&fit=crop',
    displayOrder: 5,
    status: 'Active',
  },
  {
    id: 'cat-6',
    name: 'Ceramic & Pottery',
    slug: 'ceramic-pottery',
    description: 'Wheel-thrown vases, organic textured planters, and hand-pinched glazed tableware.',
    imageUrl: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?q=80&w=1000&auto=format&fit=crop',
    displayOrder: 6,
    status: 'Active',
  },
  {
    id: 'cat-7',
    name: 'Candle Holders & Aromas',
    slug: 'candle-holders',
    description: 'Botanical wax melts, sculpted terrazzo candle stands, and hand-poured soy candles.',
    imageUrl: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?q=80&w=1000&auto=format&fit=crop',
    displayOrder: 7,
    status: 'Active',
  },
  {
    id: 'cat-8',
    name: 'Handmade Gifts',
    slug: 'handmade-gifts',
    description: 'Curated gift boxes and heartwarming handmade treasures made to celebrate special moments.',
    imageUrl: 'https://images.unsplash.com/photo-1513201099705-a9746e1e201f?q=80&w=1000&auto=format&fit=crop',
    displayOrder: 8,
    status: 'Active',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    sku: 'CG-RES-FLW-01',
    name: 'Handmade Botanical Resin Flower Display',
    slug: 'handmade-resin-flower',
    category: 'Resin Crafts',
    subcategory: 'Preserved Florals',
    shortDescription: 'Real dried wild blossoms encased in crystal-clear archival resin with hand-polished bevelled edges.',
    description: 'Each botanical resin block is an immortalization of springtime. We handpick organic wildflower buds, carefully dehydrate them in fine silica sand to preserve their vibrant natural petals, and submerge them in non-yellowing UV-resistant jewelry-grade epoxy resin. Finished with multi-grit diamond paste for an ethereal brilliance.',
    price: 1199,
    salePrice: 899,
    costPrice: 420,
    discountPercentage: 25,
    stockQuantity: 18,
    lowStockThreshold: 4,
    status: 'Active',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isCustomizable: true,
    weight: '320g',
    dimensions: '10cm x 10cm x 3cm',
    materials: 'High-clarity UV epoxy resin, naturally dried organic wild daisies, gold leaf flakes',
    careInstructions: 'Clean gently with a soft microfibre cloth. Avoid prolonged direct midday sunlight and harsh chemical cleaners.',
    deliveryInfo: 'Ships within 24-48 hours. Carefully packaged in eco-friendly gift box with foam cushioning.',
    mainImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1000&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1563245372-f21724e3856d?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop',
    ],
    rating: 4.9,
    reviewsCount: 38,
    createdAt: '2026-08-10T10:00:00Z',
    updatedAt: '2026-09-20T10:00:00Z',
  },
  {
    id: 'prod-002',
    sku: 'CG-WOD-PLQ-02',
    name: 'Personalized Calligraphy Oak Wood Plaque',
    slug: 'personalized-name-plaque',
    category: 'Personalized Gifts',
    subcategory: 'Wooden Keepsakes',
    shortDescription: 'Custom laser-engraved and hand-painted family name plaque crafted from natural reclaimed oak.',
    description: 'Celebrate milestone anniversaries, housewarmings, or newborn arrivals. Hand-carved from seasoned white oak with natural live-edge grain, finished in warm walnut stain, and inscribed with your bespoke text in raised acrylic script or deeply engraved calligraphy.',
    price: 1899,
    salePrice: 1499,
    costPrice: 650,
    discountPercentage: 21,
    stockQuantity: 12,
    lowStockThreshold: 3,
    status: 'Active',
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    isCustomizable: true,
    weight: '650g',
    dimensions: '30cm x 15cm x 2cm',
    materials: 'Solid seasoned oak wood, matte acrylic relief lettering, brass mounting hardware',
    careInstructions: 'Dust with dry lint-free cloth. Nourish every 6 months with beeswax polish.',
    deliveryInfo: 'Handcrafted on order. Dispatched within 3-4 working days.',
    mainImage: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=1000&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?q=80&w=1000&auto=format&fit=crop',
    ],
    rating: 4.8,
    reviewsCount: 29,
    createdAt: '2026-08-15T12:00:00Z',
    updatedAt: '2026-09-22T08:30:00Z',
  },
  {
    id: 'prod-003',
    sku: 'CG-MAC-WLH-03',
    name: 'Bohemian Macramé Feather Wall Hanging',
    slug: 'macrame-wall-hanging',
    category: 'Wall Art',
    subcategory: 'Fiber Art',
    shortDescription: 'Intricately knotted natural unbleached cotton cord suspended from smooth river driftwood.',
    description: 'Bring tranquil texture and grounding natural energy into your bedroom or reading nook. Knotted by hand using 100% organic combed single-twist cotton cord, shaped into cascading feather plumes, and hung from naturally tumbled driftwood collected from freshwater streams.',
    price: 2499,
    salePrice: 1899,
    costPrice: 800,
    discountPercentage: 24,
    stockQuantity: 9,
    lowStockThreshold: 3,
    status: 'Active',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isCustomizable: false,
    weight: '550g',
    dimensions: '55cm width x 70cm length',
    materials: '100% natural organic cotton cord, natural salvaged driftwood branch',
    careInstructions: 'Gently comb fringe feathers with a wide-tooth comb to maintain crisp silhouette.',
    deliveryInfo: 'Ships within 48 hours in protective tubular packaging.',
    mainImage: 'https://images.unsplash.com/photo-1522758971460-1d21eed7dc1d?q=80&w=1000&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1522758971460-1d21eed7dc1d?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=1000&auto=format&fit=crop',
    ],
    rating: 5.0,
    reviewsCount: 42,
    createdAt: '2026-07-20T10:00:00Z',
    updatedAt: '2026-09-18T14:10:00Z',
  },
  {
    id: 'prod-004',
    sku: 'CG-CER-CND-04',
    name: 'Sculptural Terrazzo Candle Holder',
    slug: 'handmade-candle-holder',
    category: 'Candle Holders & Aromas',
    subcategory: 'Concrete & Terrazzo',
    shortDescription: 'Hand-cast Jesmonite tea-light and taper candle holder speckled with terracotta fragments.',
    description: 'A tactile balance of architectural form and earthy warmth. Hand-cast from mineral-based composite resin mixed with crushed artisan terracotta ceramic shards, polished until silky smooth, and sealed with a stain-resistant matte organic wax.',
    price: 999,
    salePrice: 749,
    costPrice: 280,
    discountPercentage: 25,
    stockQuantity: 24,
    lowStockThreshold: 5,
    status: 'Active',
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    isCustomizable: true,
    weight: '400g',
    dimensions: '9cm diameter x 6cm height',
    materials: 'Eco-resin Jesmonite, recycled ceramic aggregate, cork base protector',
    careInstructions: 'Wipe clean with a damp cloth. Never submerge in water or place in dishwasher.',
    deliveryInfo: 'Includes two complimentary soy wax tea light candles.',
    mainImage: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?q=80&w=1000&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1603006905003-be475563bc59?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=1000&auto=format&fit=crop',
    ],
    rating: 4.7,
    reviewsCount: 16,
    createdAt: '2026-08-01T15:00:00Z',
    updatedAt: '2026-09-15T11:00:00Z',
  },
  {
    id: 'prod-005',
    sku: 'CG-RES-CST-05',
    name: 'Gilded Ocean Geode Resin Coasters (Set of 4)',
    slug: 'resin-coaster-set',
    category: 'Resin Crafts',
    subcategory: 'Tabletop Accents',
    shortDescription: 'Swirling deep oceanic cerulean, pearlescent white foam, and hand-gilded 24k gold leaf edges.',
    description: 'Elevate your coffee rituals and evening cocktail hours. Inspired by shoreline tidal swells, these coasters combine pigmented epoxy pigments with liquid gold accents. Heat resistant up to 90°C and backed with anti-scratch silicone stoppers.',
    price: 1599,
    salePrice: 1299,
    costPrice: 520,
    discountPercentage: 19,
    stockQuantity: 15,
    lowStockThreshold: 4,
    status: 'Active',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isCustomizable: true,
    weight: '480g',
    dimensions: '11cm diameter each (Set of 4)',
    materials: 'Food-safe heat resistant epoxy resin, mica pearlescent minerals, metallic leafing',
    careInstructions: 'Wash with mild soapy lukewarm water and soft sponge.',
    deliveryInfo: 'Tied with natural raw silk ribbon in a signature Kraft gift box.',
    mainImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1000&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1563245372-f21724e3856d?q=80&w=1000&auto=format&fit=crop',
    ],
    rating: 4.9,
    reviewsCount: 54,
    createdAt: '2026-06-12T09:00:00Z',
    updatedAt: '2026-09-19T13:45:00Z',
  },
  {
    id: 'prod-006',
    sku: 'CG-ART-CNV-06',
    name: 'Textured Minimalist Plaster Canvas Art',
    slug: 'hand-painted-canvas',
    category: 'Wall Art',
    subcategory: 'Original Canvas',
    shortDescription: 'Tactile sculptural architectural canvas painting in warm sandstone, bone, and biscuit hues.',
    description: 'An original modern artistic creation featuring layered impasto palette-knife relief strokes that catch sunlight beautifully across the day. Painted on heavy 380gsm stretched Belgian linen canvas over pine wood framing.',
    price: 3899,
    salePrice: 2999,
    costPrice: 1200,
    discountPercentage: 23,
    stockQuantity: 6,
    lowStockThreshold: 2,
    status: 'Active',
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    isCustomizable: true,
    weight: '1.4kg',
    dimensions: '50cm x 70cm x 3.5cm',
    materials: 'Organic lime plaster, archival acrylic modeling paste, stretched linen canvas, pine frame',
    careInstructions: 'Dust with soft feather duster. Avoid moisture.',
    deliveryInfo: 'Double-boxed with corner protectors. Dispatches in 2-3 business days.',
    mainImage: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=1000&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=1000&auto=format&fit=crop',
    ],
    rating: 4.9,
    reviewsCount: 19,
    createdAt: '2026-07-28T14:00:00Z',
    updatedAt: '2026-09-24T17:00:00Z',
  },
  {
    id: 'prod-007',
    sku: 'CG-GFT-BOX-07',
    name: 'Artisan Keepsake Floral Gift Hamper',
    slug: 'customized-gift-box',
    category: 'Handmade Gifts',
    subcategory: 'Curated Hampers',
    shortDescription: 'Handmade pine wood sliding box packed with botanical candle, resin pendant, and custom letter.',
    description: 'The ultimate bespoke gifting experience. Includes a hand-poured vanilla sandalwood soy candle, an encapsulated daisy resin key pendant, artisanal botanical soap bar, and a wax-sealed calligraphy parchment card with your customized message.',
    price: 2999,
    salePrice: 2499,
    costPrice: 1100,
    discountPercentage: 17,
    stockQuantity: 14,
    lowStockThreshold: 3,
    status: 'Active',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isCustomizable: true,
    weight: '900g',
    dimensions: '25cm x 20cm x 10cm',
    materials: 'Natural pine wood box, shredded jute packing, artisanal craft contents',
    careInstructions: 'Store in cool dry conditions.',
    deliveryInfo: 'Includes free personalized calligraphy greeting card.',
    mainImage: 'https://images.unsplash.com/photo-1513201099705-a9746e1e201f?q=80&w=1000&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1513201099705-a9746e1e201f?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?q=80&w=1000&auto=format&fit=crop',
    ],
    rating: 5.0,
    reviewsCount: 31,
    createdAt: '2026-08-05T09:00:00Z',
    updatedAt: '2026-09-21T12:00:00Z',
  },
  {
    id: 'prod-008',
    sku: 'CG-JWL-BOX-08',
    name: 'Carved Sheesham Wood Velvet Jewellery Box',
    slug: 'handmade-jewellery-box',
    category: 'Home Décor',
    subcategory: 'Storage & Organizers',
    shortDescription: 'Hand-carved floral filigree Sheesham wood chest lined with plush blush velvet.',
    description: 'Meticulously chiseled by master wood artisans using traditional floral fretwork. Features 4 segmented ring rolls, two earring trays, and a brass lock closure. A timeless heirloom designed to protect your most cherished trinkets.',
    price: 2199,
    salePrice: 1699,
    costPrice: 750,
    discountPercentage: 23,
    stockQuantity: 11,
    lowStockThreshold: 3,
    status: 'Active',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isCustomizable: true,
    weight: '720g',
    dimensions: '22cm x 14cm x 8cm',
    materials: 'Indian Sheesham (Rosewood), brass hinges, micro-velvet interior lining',
    careInstructions: 'Buff with dry soft cotton cloth. Keep away from excessive humidity.',
    deliveryInfo: 'Ships safely bubble-wrapped in cardboard case.',
    mainImage: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1000&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=1000&auto=format&fit=crop',
    ],
    rating: 4.8,
    reviewsCount: 22,
    createdAt: '2026-07-15T11:00:00Z',
    updatedAt: '2026-09-17T16:20:00Z',
  },
  {
    id: 'prod-009',
    sku: 'CG-CER-VAS-09',
    name: 'Wabi-Sabi Hand-Thrown Terracotta Fluted Vase',
    slug: 'decorative-clay-vase',
    category: 'Ceramic & Pottery',
    subcategory: 'Vases & Vessels',
    shortDescription: 'Wheel-thrown natural terracotta vase with tactile ribbed ridges and matte chalky slip glaze.',
    description: 'Celebrating the beauty of natural imperfections. Fired at 1050°C using rich iron-bearing terracotta clay, subtly pinched at the neck, and washed with chalky organic slip. Water-tight interior ideal for fresh botanical stems or dried pampas grass.',
    price: 1799,
    salePrice: 1399,
    costPrice: 580,
    discountPercentage: 22,
    stockQuantity: 8,
    lowStockThreshold: 2,
    status: 'Active',
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    isCustomizable: false,
    weight: '850g',
    dimensions: '18cm height x 12cm widest point',
    materials: 'Natural terracotta clay, non-toxic waterproof interior glaze',
    careInstructions: 'Hand wash only. Handle with care.',
    deliveryInfo: 'Triple-cushioned packaging with biodegradable kraft honeycomb wrap.',
    mainImage: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?q=80&w=1000&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop',
    ],
    rating: 4.9,
    reviewsCount: 14,
    createdAt: '2026-08-19T14:30:00Z',
    updatedAt: '2026-09-23T10:15:00Z',
  },
  {
    id: 'prod-010',
    sku: 'CG-PHO-FRM-10',
    name: 'Pressed Botanical Brass & Glass Floating Frame',
    slug: 'personalized-photo-frame',
    category: 'Personalized Gifts',
    subcategory: 'Memory Displays',
    shortDescription: 'Double-paned vintage glass frame bordered with antique soldered brass and real pressed ferns.',
    description: 'A charming heirloom piece that makes memories float in mid-air. Two crystal-clear glass panes are bordered with antiqued soldered brass came and an elegant hanging chain. Send us your favorite photograph to print on textured matte archival cotton rag paper.',
    price: 1299,
    salePrice: 999,
    costPrice: 420,
    discountPercentage: 23,
    stockQuantity: 16,
    lowStockThreshold: 4,
    status: 'Active',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isCustomizable: true,
    weight: '430g',
    dimensions: '15cm x 20cm (6x8 inch photo size)',
    materials: 'Dual glass panes, antique soldered brass, brass cable link chain',
    careInstructions: 'Clean glass with vinegar-water spritz on lint-free cloth.',
    deliveryInfo: 'Includes complementary photo printing on premium fine art paper.',
    mainImage: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?q=80&w=1000&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=1000&auto=format&fit=crop',
    ],
    rating: 4.7,
    reviewsCount: 27,
    createdAt: '2026-07-02T13:00:00Z',
    updatedAt: '2026-09-14T09:00:00Z',
  },
  {
    id: 'prod-011',
    sku: 'CG-DRM-CAT-11',
    name: 'Ethereal Moon Dream Catcher with Rose Quartz',
    slug: 'handmade-dream-catcher',
    category: 'Home Décor',
    subcategory: 'Spiritual Crafts',
    shortDescription: 'Crescent moon willow branch woven with metallic thread, soft goose feathers, and raw rose quartz.',
    description: 'Weave peaceful dreams and positive vibrational aura into your sanctuary. Handcrafted from steamed willow branch bent into a crescent silhouette, strung with silver embroidery filaments, and weighed with a genuine raw Madagascan rose quartz crystal point.',
    price: 1499,
    salePrice: 1149,
    costPrice: 460,
    discountPercentage: 23,
    stockQuantity: 10,
    lowStockThreshold: 3,
    status: 'Active',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    isCustomizable: false,
    weight: '280g',
    dimensions: '20cm hoop diameter x 65cm total drop',
    materials: 'Natural willow hoop, silver embroidery thread, raw rose quartz, ethically sourced feathers',
    careInstructions: 'Hang gently away from high-wind doorways.',
    deliveryInfo: 'Dispatched within 24 hours.',
    mainImage: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=1000&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=1000&auto=format&fit=crop',
    ],
    rating: 4.8,
    reviewsCount: 18,
    createdAt: '2026-08-22T10:00:00Z',
    updatedAt: '2026-09-25T15:00:00Z',
  },
  {
    id: 'prod-012',
    sku: 'CG-JWL-ERR-12',
    name: 'Artisan Terracotta & Polymer Clay Earrings',
    slug: 'handmade-polymer-earrings',
    category: 'Handmade Jewellery',
    subcategory: 'Statement Earrings',
    shortDescription: 'Ultra-lightweight statement arches sculpted from terracotta clay with 18k gold plated posts.',
    description: 'Wearable mini sculptures designed for all-day comfort. Each pair is conditioned, rolled, baked, sanded, and assembled by hand. Featherlight feel with hypoallergenic stainless steel posts dipped in 18k yellow gold.',
    price: 899,
    salePrice: 699,
    costPrice: 220,
    discountPercentage: 22,
    stockQuantity: 20,
    lowStockThreshold: 5,
    status: 'Active',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: true,
    isCustomizable: true,
    weight: '12g',
    dimensions: '5cm length x 2.8cm width',
    materials: 'Polymer modeling clay, 18k gold-plated surgical brass findings, silicone comfort backs',
    careInstructions: 'Store in jewelry pouch. Avoid spraying perfume or hairspray directly onto earrings.',
    deliveryInfo: 'Packed in a charming velvet pouch ready for gifting.',
    mainImage: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1000&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1000&auto=format&fit=crop',
    ],
    rating: 4.9,
    reviewsCount: 35,
    createdAt: '2026-08-30T16:00:00Z',
    updatedAt: '2026-09-26T12:00:00Z',
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    code: 'WELCOME10',
    discountType: 'percentage',
    discountValue: 10,
    minimumOrder: 500,
    maximumDiscount: 300,
    startDate: '2026-01-01',
    endDate: '2027-12-31',
    usageLimit: 10000,
    usedCount: 142,
    status: 'Active',
  },
  {
    code: 'CRAFTLOVE',
    discountType: 'fixed',
    discountValue: 150,
    minimumOrder: 999,
    startDate: '2026-01-01',
    endDate: '2027-12-31',
    usageLimit: 5000,
    usedCount: 88,
    status: 'Active',
  },
  {
    code: 'FESTIVE20',
    discountType: 'percentage',
    discountValue: 20,
    minimumOrder: 1999,
    maximumDiscount: 800,
    startDate: '2026-01-01',
    endDate: '2027-12-31',
    usageLimit: 2000,
    usedCount: 65,
    status: 'Active',
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-01',
    productId: 'prod-001',
    customerName: 'Ananya Sharma',
    rating: 5,
    review: 'The resin flower is even more breathtaking in person! The clear clarity and natural flowers look like drops of dew frozen in time. The packaging was so luxurious too.',
    isVerifiedPurchase: true,
    status: 'Approved',
    createdAt: '2026-09-12T14:32:00Z',
  },
  {
    id: 'rev-02',
    productId: 'prod-001',
    customerName: 'Rohit Verma',
    rating: 5,
    review: 'Gifted this to my wife on our 5th anniversary. She was genuinely touched by the craftsmanship. Worth every rupee.',
    isVerifiedPurchase: true,
    status: 'Approved',
    createdAt: '2026-09-18T10:15:00Z',
  },
  {
    id: 'rev-03',
    productId: 'prod-002',
    customerName: 'Pooja Iyer',
    rating: 5,
    review: 'Custom name plaque exceeded all expectations! The wood grain has such depth and the personalized lettering is flawless.',
    isVerifiedPurchase: true,
    status: 'Approved',
    createdAt: '2026-09-20T16:40:00Z',
  },
  {
    id: 'rev-04',
    productId: 'prod-003',
    customerName: 'Meera Sen',
    rating: 5,
    review: 'The macramé feather hanging instantly elevated my living room wall. So bohemian and grounding!',
    isVerifiedPurchase: true,
    status: 'Approved',
    createdAt: '2026-09-15T09:20:00Z',
  },
  {
    id: 'rev-05',
    productId: 'prod-005',
    customerName: 'Vikram Malhotra',
    rating: 5,
    review: 'The gold edges on these resin ocean coasters are so sleek and glamorous. Highly recommend for dining tables.',
    isVerifiedPurchase: true,
    status: 'Approved',
    createdAt: '2026-09-23T11:05:00Z',
  },
];
